### ISSUE TITLE
Fix repeating messages

### ISSUE THREAD

**Issue by tcob** [tcob/ultrachat#11]
Messages seem to repeat after a few seconds, possibly as connections are kept alive / reconnected.

![image](https://user-images.githubusercontent.com/23004666/53688090-b37b9c00-3d3e-11e9-81ea-cb830654a613.png)

**Comment by shane-t** [comment]
Will fix this. it's cos history is sent whenever the connect event happens, but it doesn't distinguish between connect and reconnect.
